################################################################# 
## Sensors 
################################################################# 

# Weather Prediction
- platform: yr

- platform: time_date
  display_options:
    - 'date_time'
    - 'time'

- platform: lastfm
  api_key: XXX
  users:
    - XXX

- platform: darksky
  api_key: XXX
  monitored_conditions:
  - summary
  - minutely_summary
  - hourly_summary
  - daily_summary
  - icon
  - nearest_storm_distance
  - nearest_storm_bearing
  - precip_type
  - precip_intensity
  - precip_probability
  - temperature
  - apparent_temperature
  - dew_point
  - wind_speed
  - wind_bearing
  - cloud_cover
  - humidity
  - pressure
  - visibility
  - ozone

- platform: cpuspeed
  name: CPU

- platform: systemmonitor
  resources:
  - type: memory_free
  - type: memory_use_percent
  - type: processor_use
  - type: since_last_boot

- platform: speedtest
  minute:
    - 0
    - 30
  monitored_conditions:
    - ping
    - download
    - upload

#- platform: plex
#  name: REDACTE 
#  host: REDACTED.101
#  port: REDACTED
#  username: REDACTED
#  password: REDACTED
#  server: REDACTED

- platform: template
  sensors:
    harmony_bedroom:
      value_template: '{{ states.remote.bedroom.attributes.current_activity }}'
      friendly_name: 'Bedroom Remote'

- platform: template
  sensors:
    harmony_family_room:
      value_template: '{{ states.remote.family_room.attributes.current_activity }}'
      friendly_name: 'Family Room Remote'

- platform: template
  sensors:
    harmony_livingroom:
      value_template: '{{ states.remote.livingroom.attributes.current_activity }}'
      friendly_name: 'Livingroom Remote'

- platform: template
  sensors:
    holidays_calendar:
      friendly_name: 'Holiday'
      value_template: '{{ states.calendar.holidays_in_united_states.attributes.message }}'

# Alarm clock
- platform: template
  sensors:
    alarm_clock_hour:
      value_template: '{{ states.input_number.alarm_clock_hour.state | int }}'
    alarm_clock_minute:
      value_template: '{{ states.input_number.alarm_clock_minute.state | int }}'
    alarm_clock_time:
      value_template: >-
        {{ states.sensor.alarm_clock_hour.state }}:
        {%- if states.sensor.alarm_clock_minute.state|length == 1 -%}
          0
        {%- endif -%}
          {{ states.sensor.alarm_clock_minute.state }}
    alarm_clock_time_long:
      value_template: >-
        {% if states.sensor.alarm_clock_hour.state|length == 1 -%}
          0
        {%- endif -%}
          {{ states.sensor.alarm_clock_hour.state }}:
        {%- if states.sensor.alarm_clock_minute.state|length == 1 -%}
          0
        {%- endif -%}
          {{ states.sensor.alarm_clock_minute.state }}

#Sensor Nodes

##Sensor Node 1
- platform: mqtt  
  state_topic: "XXX"  
  name: "SN1 Humidity"  
  unit_of_measurement: "%"  
  value_template: '{{ value_json.humidity | round(1) }}'  

- platform: mqtt  
  state_topic: "XXX"  
  name: "SN1 LDR"
  ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "LUX"  
  value_template: '{{ value_json.ldr }}'  

- platform: mqtt  
  state_topic: "XXX"  
  name: "SN1 PIR"  
  value_template: '{{ value_json.motion }}'  

- platform: mqtt  
  state_topic: "XXX"  
  name: "SN1 Temperature"  
  unit_of_measurement: "째F"  
  value_template: '{{ value_json.temperature | round(1) }}'  

- platform: mqtt
  state_topic: "XXX"
  name: "SN1 Real Feel"
  unit_of_measurement: "째F"
  value_template: '{{ value_json.heatIndex | round(1) }}'

##Sensor Node 2
- platform: mqtt  
  state_topic: "XXX"  
  name: "SN2 Humidity"  
  unit_of_measurement: "%"  
  value_template: '{{ value_json.humidity | round(1) }}'  

- platform: mqtt  
  state_topic: "XXX"  
  name: "SN2 LDR"
  ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "LUX"  
  value_template: '{{ value_json.ldr }}'  

- platform: mqtt  
  state_topic: "XXX"  
  name: "SN2 PIR"  
  value_template: '{{ value_json.motion }}'  

- platform: mqtt  
  state_topic: "XXX"  
  name: "SN2 Temperature"  
  unit_of_measurement: "째F"  
  value_template: '{{ value_json.temperature | round(1) }}'  

- platform: mqtt
  state_topic: "XXX"
  name: "SN2 Real Feel"
  unit_of_measurement: "째F"
  value_template: '{{ value_json.heatIndex | round(1) }}'

#- platform: google_travel_time
#  name: Time to Home
#  api_key: REDACTED
#  origin: device_tracker.
#  destination: zone.home
#  options:
#    mode: driving

#- platform: google_travel_time
#  name: Time to Home
#  api_key: REDACTED
#  origin: device_tracker.
#  destination: zone._home
#  options:
#    mode: walking

#- platform: google_travel_time
#  name: Time to Work
#  api_key: REDACTED
#  origin: device_tracker.
#  destination: zone.work
#  options:
#    mode: walking

#- platform: google_travel_time
#  name: Time to School
#  api_key: REDACTED
#  origin: device_tracker.
#  destination: zone._school
#  options:
#    mode: walking

#- platform: template
#  sensors:
#    _travel:
#      friendly_name: "'s Location"
#      value_template: '{% if is_state("device_tracker.", "not_home") -%} {{ states.sensor.s_time_to_home.attributes.duration }} to home{%- else -%} At {{ states("device_tracker.") }} {%- endif %}'
#
#- platform: template
#  sensors:
#    _travel:
#      friendly_name: "' Location"
#      value_template: '{% if is_state("device_tracker.", "not_home") -%} {{ states.sensor.s_time_to_home.attributes.duration }} to home{%- else -%} At {{ states("device_tracker.") }} {%- endif %}'